### ISSUE TITLE
Re-evaluate landscape mode on iPhone

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#205]
This might not be super helpful...

![untitled](https://user-images.githubusercontent.com/1757680/27965614-b4b2fe66-633c-11e7-8b52-355e02a8caf8.png)

**Comment by jprberlin** [comment]
for larger displays we have a 2 column display here .. we could start this on small screen as well

**Comment by bjrne** [comment]
Yes, I looked into this a while ago. On small screens like the iPhone 5 form factor the standard cell looks a little weird then. We should engineer another cell that looks good with little width, maybe with multiline title or date and language on top of each other. In the current configuration this looks even less helpful than this in my opinion because you barely see any textual content then as well.

**Comment by mathebox** [comment]
Related to #370

**Comment by mathebox** [comment]
closing in favor of #370
