### ISSUE TITLE
News missing after relogin

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-ios#38]
After log out and log in the news list only the global (public) news are shown and the course news are missing

**Comment by bjrne** [comment]
This is most likely not a bug in the app. Whats happening is that once you are logged in, the api is suddenly giving you course-internal-news. But since on staging.openhi.de most courses don't have news entries, it looks like the news in the app are missing while instead the api is showing non-existent news.

**Comment by jprberlin** [comment]
Franz provided an api fix
