### ISSUE TITLE
Helpdesk

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-ios#636]
Currently, we only have a technical feedback channel. We should think about proper Helpdesk integration.

**Comment by mathebox** [comment]
**Is your feature request related to a problem? Please describe.**
Instead of presenting the mail composer which sends mails to our mailing list, we should have a custom form which creates tickets in our helpdesk system.

The required fields for a helpdesk ticket are defined in the API.
https://dev.xikolo.de/api-docs/#endpoint-tickets

This form should still be accessible from the account tab (current location of the mail composer).
Additionally, we would like to have the form also accessible form within a course (as a course area) with the course field pre-filled.

**Affected Component**
AccountViewController, CourseAreaViewController, CourseAreaListViewController

**Comment by mathebox** [comment]
If the user is logged in, we can infer the mail address.
