### ISSUE TITLE
Add Course to Reminder/Calendar via Share 

### ISSUE THREAD

**Issue by cH3n7i** [openHPI/xikolo-ios#681]
**Is your feature request related to a problem? Please describe.**
There are known and important dates (e.g. new releases, deadlines,…), let's make them exportable via Share Button, so nobody can forget anything.

**Describe the solution you'd like**
While looking at the Course Details, we can export different Tasks and their dates (Reminder, Calendar, Trello,…).

**Affected Component**
`CourseDetailViewController`

**Comment by mathebox** [comment]
The web application already offers an iCal feed the user can subscribe to. Here all of the users courses dates are included. Instead of creating calendar event manually (which can be a real hassle), we should allow the user to subscribe to the iCal feed also from the app.

The URL to the iCal feed has to be made available via the API. Therefore I'm adding the `blocked` label to this issue.

<hr>

Additionally, we this about which other data can be shared from the app. See #211 for this.

**Comment by mathebox** [comment]
Closing in favor of #549 and #771
